export const otherPartnersSeedData = [
    {
      name: 'Go-Medical',
      websiteUrl: 'https://www.go-medical.ch/',
      logoUrl: '/images/go-medical-logo.png',
      hint: 'medical services logo',
      logoScale: 100,
      logoX: 0,
      logoY: 0,
      hidden: false,
    },
    {
      name: 'MCL',
      websiteUrl: 'https://www.mcl.ch/',
      logoUrl: '/images/mcl-labor-logo.png',
      hint: 'laboratory logo',
      logoScale: 100,
      logoX: 0,
      logoY: 0,
      hidden: false,
    },
    {
      name: 'doxnet',
      websiteUrl: 'https://www.doxnet.ch/',
      logoUrl: '/images/doxnet-logo.jpg',
      hint: 'medical network logo',
      logoScale: 100,
      logoX: 0,
      logoY: 0,
      hidden: false,
    },
];
