export const otherPartnersData = [
    {
      order: 1,
      name: 'Go-Medical',
      websiteUrl: 'https://www.go-medical.ch/',
      logoUrl: '/images/go-medical-logo.png',
      hint: 'medical services logo',
      width: 200,
      height: 60,
      hidden: false,
    },
    {
      order: 2,
      name: 'MCL',
      websiteUrl: 'https://www.mcl.ch/',
      logoUrl: '/images/mcl-labor-logo.png',
      hint: 'laboratory logo',
      width: 200,
      height: 60,
      hidden: false,
    },
    {
      order: 3,
      name: 'doxnet',
      websiteUrl: 'https://www.doxnet.ch/',
      logoUrl: '/images/doxnet-logo.jpg',
      hint: 'medical network logo',
      width: 200,
      height: 60,
      hidden: false,
    },
];
