
import { Doctor } from './doctor-card';

export const doctors: Doctor[] = [
  {
    id: 'ortmanns',
    title: 'Dipl. med.',
    name: 'G. Ortmanns',
    imageUrl: '/images/team/Ortmanns.jpg',
    imageHint: 'doctor portrait',
    specialty: 'Praktischer Arzt',
    qualifications: ['Master of Public Health (UNSW)', 'Master of Health Management (UNSW)'],
    additionalInfo: '(Ärztliche und administrative Leitung) Praxiszentrum im Ring',
    backsideContent: `<p>Medizinstudium in Bonn und Hobart (Australien)</p><p>Masterstudium Public Health und Health Management in Sydney (Australien)</p><p>Projektmanagement im Gesundheitswesen in Europa und Australien</p><p>Unternehmensberatung mit Spezialisierung auf den Gesundheitssektor</p><ul><li>Leiter Klinische Entwicklung und Analytik für DxCG Gesundheitsanalytik GmbH (Deutschland)</li><li>Manager für Klinische Sicherheit und Design Assurance bei der Entwicklung der Nationalen Elektronischen Gesundheitsakte in Australien</li><li>Direktor der Memory-Strategie (elektronisches Medikamenten-Management und elektronische Patientenakten) für das Netzwerk der Kinderkrankenhäuser in Sydney, Australien</li></ul><p>Weiterbildung in Allgemeiner Innerer Medizin in der Schweiz:</p><ul><li>Universitätsspital Basel (USB)</li><li>Kantonsspital Baselland (KSBL)</li><li>Kantonsspital Winterthur (KSW)</li><li>Kantonsspital Wil (SRFT)</li><li>Hausarztpraxis in Winterthur</li></ul><p>Wissenschaftlicher Mitarbeiter an der Universität Zürich / USZ (Klinik für Pneumologie)</p><p>Leitung Praxiszentrum im Ring (Ärztliche und administrative Leitung)</p><p>Lehrbeauftragter für Hausarztmedizin (Institut für Hausarztmedizin der Universität Bern)</p>`,
  },
  {
    id: 'schemmer',
    title: 'Prof. Dr. med. Dr. h. c.',
    name: 'P. Schemmer',
    imageUrl: '/images/team/Prof.Schemmer.jpg',
    imageHint: 'doctor portrait',
    specialty: 'Facharzt für Allgemein- und Viszeralchirurgie',
    partnerLogo: 'schemmer-worni',
    backsideContent: `<h4><strong>KLEINCHIRURGISCHE EINGRIFFE KÖNNEN DIREKT IM PRAXISZENTRUM IM RING ERFOLGEN</strong></h4><p><br></p><h4><strong>GROSSE CHIRURGISCHE EINGRIFFE WERDEN IN ENGER KOOPERATION ZWISCHEN CHIRURG UND HAUSARZT DURCHGEFÜHRT</strong></h4><p>Vorbesprechung und Planung des Eingriffs erfolgen im PRAXISZENTRUM IM RING</p><p>Allenfalls notwendige Abklärungen vor dem Eingriff finden ebenfalls im Praxiszentrum statt oder – falls nötig – per Überweisung an weitere Spezialisten</p><p>Die Operation selbst findet in einer der Partnerkliniken in der Stadt Bern statt</p><ul><li>Hirslanden</li><li>Lindenhof-Spital</li><li>Siloah-Spital</li></ul><p>Die Nachbetreuung (z. B. Fadenentfernung und Schmerzbehandlung) findet wieder im PRAXISZENTRUM IM RING statt</p>`,
  },
  {
    id: 'rosenov',
    title: 'Dr. med.',
    name: 'A. Rosenov',
    imageUrl: '/images/team/Dr.Rosenov.jpg',
    imageHint: 'doctor portrait',
    specialty: 'Facharzt für Angiologie',
    partnerLogo: 'vasc-alliance',
    backsideContent: `<h4><strong>UNTERSUCHUNGEN DER VENEN, ARTERIEN UND LYMPHGEFÄSSE</strong></h4><h4><strong>ABKLÄRUNG VON EREKTIONSSTÖRUNGEN</strong></h4><p><br></p><p>Viele Untersuchungen und Abklärungen können direkt im PRAXISZENTRUM IM RING durchgeführt werden.</p><p>Sind zusätzliche Spezialuntersuchungen oder weiterführende Eingriffe nötig, die mit den Geräten im Praxiszentrum nicht durchführbar sind, wird ein Folgetermin in den Räumlichkeiten der VASC ALLIANCE am Beau-site Spital in Bern vereinbart.</p>`,
  },
  {
    id: 'herschel',
    title: 'Dr. med.',
    name: 'R. Herschel',
    imageUrl: '/images/team/Dr.Herschel.jpg',
    imageHint: 'doctor portrait',
    specialty: 'Facharzt für Orthopädische Chirurgie und Traumatologie des Bewegungsapparates',
    partnerLogo: 'orthozentrum',
    backsideContent: `<h4><strong>ALLGEMEINE ORTHOPÄDIE</strong></h4><h4><strong>SPEZIALGEBIET HÜFT- UND KNIEGELENKE</strong></h4><p><br></p><p>Röntgenuntersuchungen, Konsultationen und klinische Untersuchungen finden direkt vor Ort im PRAXISZENTRUM IM RING statt.</p><p>Auch Gelenkinfiltrationen, z. B. bei Schmerzen, können zum Teil direkt vor Ort durchgeführt werden.</p><p>Allenfalls nötige Operationen werden im gut erreichbaren Lindenhof-Spital durchgeführt.</p>`,
  },
  {
    id: 'slezak',
    title: 'Dr. med.',
    name: 'A. Slezak',
    imageUrl: '/images/team/Dr.Slezak.jpg',
    imageHint: 'doctor portrait',
    specialty: 'Fachärztin für Neurologie',
    partnerLogo: 'slezak',
    backsideContent: `<h4><strong>ALLGEMEINE NEUROLOGIE</strong></h4><h4><strong>VASKULÄRE ERKRANKUNGEN</strong></h4><h4><strong>EPILEPSIE</strong></h4><h4><strong>BEWEGUNGSSTÖRUNGEN (Schwerpunkt Parkinsonsyndrome)</strong></h4><h4><strong>KOPFSCHMERZEN UND MIGRÄNE</strong></h4><h4><strong>NEUROREHABILITATION</strong></h4><p><br></p><p>Viele Untersuchungen können direkt im PRAXISZENTRUM IM RING durchgeführt werden.</p><p>Wenn spezielle Untersuchungen wie z. B. die Bestimmung der Nervenleitgeschwindigkeit Geräte erfordern, die im PRAXISZENTRUM IM RING nicht zur Verfügung stehen, dann finden diese in den Räumlichkeiten an der Thunstrasse 95 in Bern statt.</p>`,
  },
];
